# Generated by Django 4.1.7 on 2023-03-27 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='List.list')),
                ('fk_id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='List.product')),
            ],
        ),
    ]
