# Generated by Django 4.1.7 on 2023-04-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0003_rename_fk_id_list_productslist_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supermarket',
            name='address',
        ),
        migrations.AddField(
            model_name='productslist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
